import { test, _electron as electron } from '@playwright/test';
import { createServer } from 'node:http';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { cartellaTemporanea } from '../../helpers/percorsi.mjs';
import { argomentiScala } from '../../helpers/scala.mjs';
import { chiudiApp } from '../../fixtures/electron.mjs';
import { captureComposite } from '../../agent/driver.mjs';
const APP_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..');
test('toast sopra pagina', async () => {
  test.setTimeout(60000);
  const server = createServer((q, r) => { r.writeHead(200, { 'Content-Type': 'text/html' }); r.end('<body style="background:#3a6"><h1>pagina</h1></body>'); });
  await new Promise((ok) => server.listen(0, '127.0.0.1', ok));
  const app = await electron.launch({ args: [...argomentiScala, '.'], cwd: APP_ROOT, env: { ...process.env, FILO_USER_DATA: cartellaTemporanea('filo-scr-'), NODE_ENV: 'test' } });
  const shell = await app.firstWindow();
  await shell.waitForLoadState('domcontentloaded');
  await new Promise((ok) => setTimeout(ok, 1000));
  await shell.evaluate((u) => window.filoShell.tabs.open(u), `http://127.0.0.1:${server.address().port}/`);
  await new Promise((ok) => setTimeout(ok, 2500));
  await app.evaluate(({ BrowserWindow }) => { for (const w of BrowserWindow.getAllWindows()) if (w._filoTabs) w.webContents.send('shell:toast', { text: 'PROVA TOAST sopra la pagina', opts: { durationSec: 0, actions: [{ label: 'Consenti' }] } }); });
  await new Promise((ok) => setTimeout(ok, 800));
  await captureComposite(app, '/tmp/claude-0/-home-user-Filo/0b2a3cbc-29d6-5011-a412-bcfc304fcb93/scratchpad/toast.png');
  await chiudiApp(app); server.close();
});
